Vagrant.configure("2") do |config|

  config.ssh.forward_agent = true
   config.vm.box = "centos/7"
  # config.vm.box = "ubuntu/xenial64"
  # config.vm.box = "ubuntu/bionic64"
  #config.vm.box = "debian/jessie64"
  # config.vm.box = "debian/stretch64"
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "setup_fail2ban.yml"
    ansible.verbose = true
  end
end
