---
- name: Install epel-release on Red Hat based systems
  yum:
    name: epel-release
    update_cache: true
  become: true
  when: ansible_os_family == "RedHat"

- name: Auto update and upgrade Debian os systems
  apt:
    update_cache: yes
  become: true
  when: ansible_os_family == "Debian"

- name: Install fail2ban
  package:
    name: fail2ban
  become: true

- name: Copy sshd.local
  template:
    src: "{{ item }}"
    dest: /etc/fail2ban/jail.d
    force: yes
    owner: root
    group: root
    mode: 644
  notify: restart_fail2ban
  become: true
  with_fileglob:
      - ../templates/*.local
