controller:
  replicaCount: 2
  service:
    loadBalancerIP: 1.1.1.1
    externalTrafficPolicy: Local
  addHeaders:
    X-Frame-Options: "SAMEORIGIN"
    X-XSS-Protection: "1; mode=block"
    X-Content-Type-Options: "nosniff"
