version: '2'
services:

  zabbix-db:
    image: monitoringartist/zabbix-db-mariadb
    volumes:
      - ./db:/var/lib/mysql
      - ./dbbackups:/backups
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MARIADB_USER=test
      - MARIADB_PASS=test
    networks:
      - balancernetwork
    restart: always

  zabbix-server:
    image: monitoringartist/zabbix-xxl:latest
    container_name: zabbix
    ports:
      - 10051:10051
      - 8080:80
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - XXL_zapix=true
      - XXL_grapher=true
      - XXL_apiuser=test
      - XXL_apipass=test
      - ZS_DBHost=zabbix-db
      - ZS_DBUser=test
      - ZS_DBPassword=test
    networks:
      - balancernetwork
    restart: always
    ulimits:
     nproc: 65535
     nofile:
       soft: 20000
       hard: 40000

networks:
  balancernetwork:
    external:
      name: balancernetwork

