apiVersion: cert-manager.io/v1alpha2 #certmananger.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    # You must replace this email address with your own.
    # Let's Encrypt will use this to contact you about expiring
    # certificates, and issues related to your account.
    email: dpiddubnyi@dxc.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource used to store the account's private key.
      name: letsencrypt-stg-issuer-account-key
    solvers:
    - dns01:
        azuredns:
          clientID: {{ .Values.azuredns.sp_app_id }}
          clientSecretSecretRef:
          # The following is the secret we created in Kubernetes. Issuer will use this to present challenge to Azure DNS.
            name: {{ .Values.azuredns.dns_token_name }}
            key: client-secret
          subscriptionID: {{ .Values.azure.subscription_id }}
          tenantID: {{ .Values.azure.tenant_id }}
          resourceGroupName: {{ .Values.azuredns.dns_zone_rg }}
          hostedZoneName: {{ .Values.azuredns.dns_zone }}
          # Azure Cloud Environment, default to AzurePublicCloud
          environment: AzurePublicCloud
---
apiVersion: cert-manager.io/v1alpha2 #certmananger.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    # You must replace this email address with your own.
    # Let's Encrypt will use this to contact you about expiring
    # certificates, and issues related to your account.
    email: dpiddubnyi@dxc.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource used to store the account's private key.
      name: letsencrypt-issuer-account-key
    solvers:
    - dns01:
        azuredns:
          clientID: {{ .Values.azuredns.sp_app_id }}
          clientSecretSecretRef:
          # The following is the secret we created in Kubernetes. Issuer will use this to present challenge to Azure DNS.
            name: {{ .Values.azuredns.dns_token_name }}
            key: client-secret
          subscriptionID: {{ .Values.azure.subscription_id }}
          tenantID: {{ .Values.azure.tenant_id }}
          resourceGroupName: {{ .Values.azuredns.dns_zone_rg }}
          hostedZoneName: {{ .Values.azuredns.dns_zone }}
          # Azure Cloud Environment, default to AzurePublicCloud
          environment: AzurePublicCloud
