---
######################################################
### Change to value of port which used in          ###
### the remote machine                             ###
######################################################
ssh_port: 22
