version: '2'

services:
  artifactory:
    image: docker.bintray.io/jfrog/artifactory-pro:5.9.7
    container_name: artifactory
    ports:
     - 8081:8081
    restart: always
    volumes:
     - ./.artifactory:/var/opt/jfrog/artifactory
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
